/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.examplejdbc.bd.view;

/**
 *
 * @author rojas
 */
public class JFrameHome extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonEmployeeType = new javax.swing.JButton();
        jButtonEmployee = new javax.swing.JButton();
        jButtonKey = new javax.swing.JButton();
        jButtonRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        setBackground(new java.awt.Color(0, 102, 51));

        jPanelHome.setBackground(new java.awt.Color(0, 102, 51));
        jPanelHome.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Master Key 1.0");

        jButtonEmployeeType.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEmployeeType.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonEmployeeType.setForeground(new java.awt.Color(0, 102, 51));
        jButtonEmployeeType.setText("Tipos de Funcionarios");
        jButtonEmployeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeTypeActionPerformed(evt);
            }
        });

        jButtonEmployee.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEmployee.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonEmployee.setForeground(new java.awt.Color(0, 102, 51));
        jButtonEmployee.setText("Funcionarios");
        jButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeActionPerformed(evt);
            }
        });

        jButtonKey.setBackground(new java.awt.Color(255, 255, 255));
        jButtonKey.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonKey.setForeground(new java.awt.Color(0, 102, 51));
        jButtonKey.setText("Llaves");
        jButtonKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeyActionPerformed(evt);
            }
        });

        jButtonRecord.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRecord.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonRecord.setForeground(new java.awt.Color(0, 102, 51));
        jButtonRecord.setText("Registros");
        jButtonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(130, 130, 130))
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEmployeeType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(35, 35, 35)
                .addComponent(jButtonEmployeeType)
                .addGap(18, 18, 18)
                .addComponent(jButtonEmployee)
                .addGap(18, 18, 18)
                .addComponent(jButtonKey)
                .addGap(18, 18, 18)
                .addComponent(jButtonRecord)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmployeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeTypeActionPerformed
        JFrameEmployeeType view = new JFrameEmployeeType();
        view.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonEmployeeTypeActionPerformed

    private void jButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeActionPerformed
        JFrameEmployee view = new JFrameEmployee();
        view.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonEmployeeActionPerformed

    private void jButtonKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeyActionPerformed
       JFrameKeys view = new JFrameKeys();
        view.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonKeyActionPerformed

    private void jButtonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordActionPerformed
       JFrameRecord view = new JFrameRecord();
        view.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEmployee;
    private javax.swing.JButton jButtonEmployeeType;
    private javax.swing.JButton jButtonKey;
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelHome;
    // End of variables declaration//GEN-END:variables
}
